# Generated by Django 3.1 on 2020-08-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcity', models.IntegerField()),
                ('idcountry', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('is_courrier', models.BooleanField()),
                ('idstate', models.IntegerField()),
                ('isdelivery', models.BooleanField()),
                ('active', models.BooleanField()),
                ('consultado', models.DateTimeField(auto_now_add=True)),
                ('editado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
