# Generated by Django 3.1 on 2020-08-28 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socrates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['idcity']},
        ),
    ]
