# Generated by Django 3.1 on 2020-08-29 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socrates', '0002_auto_20200827_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consulta',
            new_name='fb_city',
        ),
    ]
