# Generated by Django 3.1 on 2020-08-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socrates', '0003_auto_20200828_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fb_city',
            options={},
        ),
    ]
