# Generated by Django 3.1 on 2020-08-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socrates', '0004_auto_20200828_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fb_city',
            name='name',
        ),
    ]
